# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew clean shadowJar -x test

      - name: Run Tests
        run: ./gradlew test

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the commit hash
        id: commit_hash
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t l1zail/sharding-client:${{ env.COMMIT_HASH }} -f Dockerfile .

      - name: Push Docker image
        run: |
          docker push l1zail/sharding-client:${{ env.COMMIT_HASH }}

      - name: Tag Docker image as latest
        run: |
          docker tag l1zail/sharding-client:${{ env.COMMIT_HASH }} l1zail/sharding-client:latest

      - name: Push Docker image as latest
        run: |
          docker push l1zail/sharding-client:latest     

